### ISSUE TITLE
Config file will not save

### ISSUE THREAD

**Issue by Zunwolf1896** [27rogi/Fabric2Discord#15] opened 2022-10-09 13:26 UTC
I instal the mod, the latest 1.19 version into the server, restartt the server, stop the server, go into the ocnfigs to edit and add bot token etc, save the config restart the server, server crashes check the config file and it has not saved a single thing I did. its saved as settings.conf iniside of configs/f2d/settings.conf 

Everytime I start the server it deletes the config and replaces it with a new unedited one making this mod unusable the following is the error I receive when starting the server:

`main/ERROR Failed to start the minecraft server
09.10 13:32:02 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'f2d'!
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO Caused by: java.lang.Error: You must provide Discord API token for this mod to work!
09.10 13:32:02 [Server] INFO at space.ryzhenkov.Fabric2Discord.F2D.onInitialize(F2D.kt:14) ~[Fabric2Discord-1.0.5+1.19.jar:?]
09.10 13:32:02 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
09.10 13:32:02 [Server] INFO ... 7 more`

**Comment by finnnnnnnnnnnnnnnnn** [comment] 2022-10-31 01:40
I am also having the same issue, which seems to be caused by using webhooks. Setting webhook to anything other than 0 causes the server to crash.

**Comment by 27rogi** [comment] 2022-10-31 08:53
> I am also having the same issue, which seems to be caused by using webhooks. Setting webhook to anything other than 0 causes the server to crash.

Can you provide server logs?

**Comment by some16** [comment] 2022-10-31 19:46
https://pastebin.com/ErbYGuq8

**Comment by finnnnnnnnnnnnnnnnn** [comment] 2022-10-31 19:48
https://pastebin.com/wU1E7YTD

**Comment by 27rogi** [comment] 2022-10-31 19:49
> https://pastebin.com/wU1E7YTD

Error message `REST request returned an error: 400 Bad Request  Invalid Form Body {"name":{"_errors":[{"code":"USERNAME_INVALID_CONTAINS","message":"Username cannot contain \"discord\""}]}}` clearly says that you are trying to use bot or webhook with username `discord`, try changing it to something else 🤔

**Comment by finnnnnnnnnnnnnnnnn** [comment] 2022-11-01 01:24
I don't really know what to change, my bot is named Minecraft Link, and so is my webhook. Is there something in the bot's config file I should change? I don't see anything.

**Comment by finnnnnnnnnnnnnnnnn** [comment] 2022-11-03 10:31
Also, @Zunwolf1896  it looks like your issue is caused by you not configuring the mod correctly. You need to add an API token, as it states in the output log: `You must provide Discord API token for this mod to work!` The instructions are here: https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started

EDIT: Just realized you said you couldn't change the config file. Nevermind.

**Comment by 27rogi** [comment] 2022-11-04 06:49
> I don't really know what to change, my bot is named Minecraft Link, and so is my webhook. Is there something in the bot's config file I should change? I don't see anything.

Could you try to create another bot and use it's token and check if mod works?
Also I remember that mod can automatically generate webhooks when `webhook` is set to `-1`

**Comment by 27rogi** [comment] 2022-12-27 23:52
Closing this issue because there's no more activity and new info.

**Closed as completed by 27rogi** 2022-12-27 23:52 UTC
Labels: bug
