### ISSUE TITLE
Netty IP resolve crash

### ISSUE THREAD

**Issue by Shadowrs** [27rogi/Fabric2Discord#5] opened 2022-08-04 11:04 UTC
mc 1.18.2
Fabric2Discord-1.0.3+1.18
stops server from launching
only configs i changed:
```
chatChannel=123
        # Snowflake (id) of the channel used for join, leave, death and etc. messages
        # More on https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started#basic-setup=
        logChannel=123
        # Snowflake (id) of the webhook used to send Minecraft messages using player data
        # More on https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started#connecting-webhook=
        webhook=123

token="xx.xx.xx_xx"
```

```[11:53:42] [main/INFO]: Successfully loaded config file.
[11:53:43] [main/INFO]: Discord4J 3.2.2 (https://discord4j.com)
[11:53:44] [reactor-http-nio-2/WARN]: A task raised an exception. Task: reactor.netty.transport.TransportConnector$MonoChannelPromise$$Lambda$12677/0x0000000802116708@2b572628
java.lang.NoSuchMethodError: 'java.net.InetAddress io.netty.util.NetUtil.createInetAddressFromIpAddressString(java.lang.String)'
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1064) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1048) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158) ~[netty-all-4.1.68.Final.jar:?]
        at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:339) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:162) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[io_projectreactor_reactor-core-3.5.0-M2-1ac58bde331c9f33.jar:?]
        at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:636) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:556) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.68.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by 27rogi** [comment] 2022-08-04 11:14
Looks like you are trying to use `123` as id which is not correct `Snowflake` for Discord channel.
If you want to disable specified channel use `0`

**Comment by SajmonOriginal** [comment] 2022-08-04 12:28
I have the same problem, but the ids are correct

**Comment by Shadowrs** [comment] 2022-08-04 13:18
`123` was dummy data, i've put the correct channel id in.
edit: since `at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]` is not helpful i'll remove NEC later and retry and check if I get a better stacktrace

**Comment by 27rogi** [comment] 2022-08-04 14:29
> I have the same problem, but the ids are correct

Can you provide server logs and game version?

**Comment by 27rogi** [comment] 2022-08-04 14:31
I can't reproduce this issue on the Fabric 1.19.1 server

**Comment by Shadowrs** [comment] 2022-08-04 18:41
I removed not enough crashes- didnt improve stacktrace. same netty issue. failing to convert a String to an IP .. I'm not on vpn and the only string related stuff from the Config file is image/imaegHeader for discord messages. 

i removed all the URLs in
`iconFooter=""
        iconHeader=""
        image=""`

but the issue is still there so thats not the cause

```[19:35:59] [reactor-http-nio-2/WARN]: A task raised an exception. Task: reactor.netty.transport.TransportConnector$MonoChannelPromise$$Lambda$12656/0x00000008020e6000@6b4a13aa
java.lang.NoSuchMethodError: 'java.net.InetAddress io.netty.util.NetUtil.createInetAddressFromIpAddressString(java.lang.String)'
        at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1064) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1048) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158) ~[netty-all-4.1.68.Final.jar:?]
        at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:339) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:162) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[io_projectreactor_reactor-core-3.5.0-M2-1ac58bde331c9f33.jar:?]
        at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:636) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:556) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.68.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by SajmonOriginal** [comment] 2022-08-04 20:58
> 
Game Version: Minecraft 1.18.2
Fabric Version: Fabric Loader 0.14.8
Server Log: https://mclo.gs/kkQBW07


Error:
`[20:52:38] [reactor-http-epoll-2/WARN]: A task raised an exception. Task: reactor.netty.transport.TransportConnector$MonoChannelPromise$$Lambda$6594/0x0000000801b64d08@2a4f2c31
java.lang.NoSuchMethodError: 'java.net.InetAddress io.netty.util.NetUtil.createInetAddressFromIpAddressString(java.lang.String)'
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1064) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1048) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56) ~[io_netty_netty-resolver-dns-4.1.77.Final-dd6424286476d27b.jar:?]
	at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158) ~[netty-all-4.1.68.Final.jar:?]
	at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:339) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
	at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:162) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[io_projectreactor_reactor-core-3.5.0-M2-1ac58bde331c9f33.jar:?]
	at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:636) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
	at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:556) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-df592494a2f9564b.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by SajmonOriginal** [comment] 2022-08-08 02:58
I found that this happens even without any other mods.. purely Fabric2Discord and FabricAPI

**Comment by 27rogi** [comment] 2022-08-08 09:02
> I found that this happens even without any other mods.. purely Fabric2Discord and FabricAPI

Thanks for the info, I will try to replicate the problem.

**Comment by 27rogi** [comment] 2022-08-15 12:13
Hi, I changed Discord library from D4J to kord, could you download latest 2.0.0 beta and check if it works for you?

**Comment by DefenderYAY** [comment] 2022-08-15 15:47
> Hi, I changed Discord library from D4J to kord, could you download latest 2.0.0 beta and check if it works for you?
This is a new 1.19.2 Fabric Server: 
[latest.log](https://github.com/rogi27/Fabric2Discord/files/9338293/latest.log)

**Comment by 27rogi** [comment] 2022-08-15 15:48
Ooops, seems like I forgot to bundle another library

**Comment by DefenderYAY** [comment] 2022-08-15 15:53
> Ooops, seems like I forgot to bundle another library

WHOOPS

**Comment by 27rogi** [comment] 2022-08-15 16:04
New version released, try it

**Comment by DefenderYAY** [comment] 2022-08-15 16:12
> New version released, try it

uh
[latest.log](https://github.com/rogi27/Fabric2Discord/files/9338430/latest.2.log)

**Comment by 27rogi** [comment] 2022-08-15 16:50
> > New version released, try it
> 
> uh [latest.log](https://github.com/rogi27/Fabric2Discord/files/9338430/latest.2.log)

Something is blocking connection on your side, this explains why other mod was unable to connect.

**Comment by DefenderYAY** [comment] 2022-08-16 10:27
> > New version released, try it
> 
> uh [latest.log](https://github.com/rogi27/Fabric2Discord/files/9338430/latest.2.log)

**Update:** 
It seems to send the world started message before crashing with this: 
```
[16:43:09] [Timer-1/ERROR]: Uncaught exception in thread "Timer-1"
kotlin.UninitializedPropertyAccessException: lateinit property socket has not been initialized
at dev.kord.gateway.DefaultGateway.sendUnsafe(DefaultGateway.kt:284) ~[f2d-2.0.1-beta+1.19.2.jar:?]
at dev.kord.gateway.DefaultGateway.send(DefaultGateway.kt:267) ~[f2d-2.0.1-beta+1.19.2.jar:?]
at dev.kord.core.cache.CachingGateway.send(CachingGateway.kt) ~[dev_kord_kord-core-0.8.0-M15-d18942067fb2a34b.jar:?]
at dev.kord.core.gateway.MasterGateway$DefaultImpls.sendAll(MasterGateway.kt:34) ~[dev_kord_kord-core-0.8.0-M15-d18942067fb2a34b.jar:?]
at dev.kord.core.gateway.DefaultMasterGateway.sendAll(DefaultMasterGateway.kt:12) ~[dev_kord_kord-core-0.8.0-M15-d18942067fb2a34b.jar:?]
at space.ryzhenkov.fabric2discord.ktmixins.MinecraftServerMixin$afterSetupServer$2$run$1.invokeSuspend(MinecraftServerMixin.kt:50) ~[f2d-2.0.1-beta+1.19.2.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
at space.ryzhenkov.fabric2discord.ktmixins.MinecraftServerMixin$afterSetupServer$2.run(MinecraftServerMixin.kt:28) ~[f2d-2.0.1-beta+1.19.2.jar:?]
at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[16:43:24] [DefaultDispatcher-worker-5/WARN]: retry limit exceeded, gateway closing
```
![image](https://user-images.githubusercontent.com/107358273/184678613-69847dfe-ed2a-4bbf-ada6-9dfb10b8e7e0.png)

**Comment by DefenderYAY** [comment] 2022-08-16 10:27
> Something is blocking connection on your side, this explains why other mod was unable to connect.

ah, i'll see what i can do

**Comment by serega404** [comment] 2022-08-17 02:31
I also encountered a similar problem on 1.18.2

Server country: Russia (Discord work)
Current server OS: Windows 10 x64

Log:
`[05:12:53] [reactor-http-nio-2/WARN]: A task raised an exception. Task: reactor.netty.transport.TransportConnector$MonoChannelPromise$$Lambda$6954/0x0000000801bbf188@ddb36bf                 java.lang.NoSuchMethodError: 'java.net.InetAddress io.netty.util.NetUtil.createInetAddressFromIpAddressString(java.lang.String)'                                                                      at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1064) ~[io_netty_netty-resolver-dns-4.1.77.Final-4b6a74de0b01ea14.jar:?]                                           at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:1048) ~[io_netty_netty-resolver-dns-4.1.77.Final-4b6a74de0b01ea14.jar:?]                                           at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79) ~[netty-all-4.1.68.Final.jar:?]                                                                                at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96) ~[io_netty_netty-resolver-dns-4.1.77.Final-4b6a74de0b01ea14.jar:?]                                        at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71) ~[io_netty_netty-resolver-dns-4.1.77.Final-4b6a74de0b01ea14.jar:?]                                     at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56) ~[io_netty_netty-resolver-dns-4.1.77.Final-4b6a74de0b01ea14.jar:?]                                     at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73) ~[netty-all-4.1.68.Final.jar:?]                                                                at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31) ~[netty-all-4.1.68.Final.jar:?]                                                                at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158) ~[netty-all-4.1.68.Final.jar:?]                                                                     at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:339) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-aff1e4408e96743d.jar:?]                          at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:162) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-aff1e4408e96743d.jar:?]                             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[io_projectreactor_reactor-core-3.5.0-M2-c5249a90b7b8ec03.jar:?]                                              at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:636) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-aff1e4408e96743d.jar:?]                at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:556) ~[io_projectreactor_netty_reactor-re-1.1.0-M2-aff1e4408e96743d.jar:?]                                                                                                                                                                                                      at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]                                                                  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]                                                          at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]                                                                                                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]                                                                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]                                                                                   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.68.Final.jar:?]                                                                       at java.lang.Thread.run(Thread.java:833) [?:?]    `

**Comment by SajmonOriginal** [comment] 2022-08-17 07:03
I can't find 1.18.2 version of your 2.0.0 Beta

**Comment by 27rogi** [comment] 2022-08-17 12:21
> I can't find 1.18.2 version of your 2.0.0 Beta

There is no 2.0.0 version for 1.18.2 yet

**Comment by 27rogi** [comment] 2022-08-17 17:51
@SajmonOriginal @serega404
I ported current 1.19.2 build to 1.18.2, should be already uploaded to Modrinth and CurseForge.

**Comment by SajmonOriginal** [comment] 2022-08-18 13:20
Hi... so everything works as it should, except that the messages from Discord to Minecraft don't work.. no error is displayed, just nothing happens.

**Comment by 27rogi** [comment] 2022-08-18 14:45
> Hi... so everything works as it should, except that the messages from Discord to Minecraft don't work.. no error is displayed, just nothing happens.

Hmm... Will try to reproduce it and see what I can do with it.

**Comment by 27rogi** [comment] 2022-08-20 11:18
I pushed update that should fix problem with the messages, try it out and give feedback.

**Comment by SajmonOriginal** [comment] 2022-08-23 21:32
Thanks, problem fixed.. you can close this issue 😊

**Closed as completed** 2022-08-23 22:17 UTC
Labels: bug, help wanted
